packages:
  - "apps/*"
  - "packages/*"

verifyDepsBeforeRun: false

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  unrs-resolver: true
